In [1]:
import numpy as np
out=np.array([0,0,1,0,1,1,0]) #sunny=0, cloudy=1
temp=np.array([0,1,1,1,0,0,0]) #cold=0, warm=1
rtn=np.array([0,1,0,0,0,1,1]) #indoor=0, outdoor= 1
cot=np.array([0,0,0,0,1,1,1]) #no=0, yes=1

print('Outlook:',out.size,'| Temp:',temp.size ,'| Routine:',rtn.size,'| Coat:',cot.size)


Outlook: 7 | Temp: 7 | Routine: 7 | Coat: 7


In [2]:
c11 = np.transpose(np.nonzero(cot)) 
print(c11)

o1=out[4:]
t1=temp[4:]
r1=rtn[4:]

[[4]
 [5]
 [6]]


In [3]:
o11 =np.argwhere(o1==1)
t11 =np.argwhere(t1==1)
r11 =np.argwhere(r1==1)

o111 = np.argwhere(out==1)
t111 = np.argwhere(temp==1)
r111 = np.argwhere(rtn==1)
len(r111)


C_yes = ((o11.size/o1.size)*(t11.size/t1.size)*(r11.size/r1.size)*(c11.size/cot.size)) / ((o111.size/out.size)*(t111.size/temp.size)*(r111.size/rtn.size))
print("P( C =yes | x ) = ",C_yes)

P( C =yes | x ) =  0.0


In [4]:
c22 = np.argwhere(cot == 0)
print(c22)

[[0]
 [1]
 [2]
 [3]]


In [5]:
o2=out[:4]
print(o2)

t2=temp[:4]
print(t2)

r2=rtn[:4]
print(r2)

[0 0 1 0]
[0 1 1 1]
[0 1 0 0]


In [9]:
o22 =np.argwhere(o2==1)

t22 =np.argwhere(t2==1)
r22 =np.argwhere(r2==1)
o222 = np.argwhere(out==1)
t222 = np.argwhere(temp==1)
r222 = np.argwhere(rtn==1)
t22.size

3

In [7]:
C_no = ((o22.size/o2.size)*(t22.size/t2.size)*(r22.size/r2.size)*(c22.size/cot.size))/((o222.size/out.size)*(t222.size/temp.size)*(r222.size/rtn.size))
print("P( C = no | x )  = ",C_no)

P( C = no | x )  =  0.3402777777777778


In [8]:
if(C_no>C_yes):
    print ("Wear coat = no")
else:
    print("Wear coat = yes")

Wear coat = no
